#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.1 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Fri Apr 24 01:15:29 CDT 2020
# SW Build 2552052 on Fri May 24 14:47:09 MDT 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xelab -wto 36c7e40d297b4da3a2f28dbff2fda4d8 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip -L xpm --snapshot TB_Serializer_behav xil_defaultlib.TB_Serializer -log elaborate.log"
xelab -wto 36c7e40d297b4da3a2f28dbff2fda4d8 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip -L xpm --snapshot TB_Serializer_behav xil_defaultlib.TB_Serializer -log elaborate.log

