# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/digilent-xdc-master/Arty-Z7-20-Master.xdc

# Block Designs: bd/bd1/bd1.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd1 || ORIG_REF_NAME==bd1} -quiet] -quiet

# IP: bd/bd1/ip/bd1_xlconstant_13_0/bd1_xlconstant_13_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd1_xlconstant_13_0 || ORIG_REF_NAME==bd1_xlconstant_13_0} -quiet] -quiet

# IP: bd/bd1/ip/bd1_xlconstant_9_0/bd1_xlconstant_9_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd1_xlconstant_9_0 || ORIG_REF_NAME==bd1_xlconstant_9_0} -quiet] -quiet

# IP: bd/bd1/ip/bd1_xlconstant_14_0/bd1_xlconstant_14_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd1_xlconstant_14_0 || ORIG_REF_NAME==bd1_xlconstant_14_0} -quiet] -quiet

# IP: bd/bd1/ip/bd1_xlconstant_15_0/bd1_xlconstant_15_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd1_xlconstant_15_0 || ORIG_REF_NAME==bd1_xlconstant_15_0} -quiet] -quiet

# IP: bd/bd1/ip/bd1_xlconstant_0_0/bd1_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd1_xlconstant_0_0 || ORIG_REF_NAME==bd1_xlconstant_0_0} -quiet] -quiet

# IP: bd/bd1/ip/bd1_xlconstant_1_0/bd1_xlconstant_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd1_xlconstant_1_0 || ORIG_REF_NAME==bd1_xlconstant_1_0} -quiet] -quiet

# IP: bd/bd1/ip/bd1_xlconstant_2_0/bd1_xlconstant_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd1_xlconstant_2_0 || ORIG_REF_NAME==bd1_xlconstant_2_0} -quiet] -quiet

# IP: bd/bd1/ip/bd1_xlconstant_3_0/bd1_xlconstant_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd1_xlconstant_3_0 || ORIG_REF_NAME==bd1_xlconstant_3_0} -quiet] -quiet

# IP: bd/bd1/ip/bd1_xlconstant_4_0/bd1_xlconstant_4_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd1_xlconstant_4_0 || ORIG_REF_NAME==bd1_xlconstant_4_0} -quiet] -quiet

# IP: bd/bd1/ip/bd1_xlconstant_5_0/bd1_xlconstant_5_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd1_xlconstant_5_0 || ORIG_REF_NAME==bd1_xlconstant_5_0} -quiet] -quiet

# IP: bd/bd1/ip/bd1_xlconstant_10_0/bd1_xlconstant_10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd1_xlconstant_10_0 || ORIG_REF_NAME==bd1_xlconstant_10_0} -quiet] -quiet

# IP: bd/bd1/ip/bd1_xlconstant_6_0/bd1_xlconstant_6_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd1_xlconstant_6_0 || ORIG_REF_NAME==bd1_xlconstant_6_0} -quiet] -quiet

# IP: bd/bd1/ip/bd1_xlconstant_11_0/bd1_xlconstant_11_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd1_xlconstant_11_0 || ORIG_REF_NAME==bd1_xlconstant_11_0} -quiet] -quiet

# IP: bd/bd1/ip/bd1_xlconstant_7_0/bd1_xlconstant_7_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd1_xlconstant_7_0 || ORIG_REF_NAME==bd1_xlconstant_7_0} -quiet] -quiet

# IP: bd/bd1/ip/bd1_xlconstant_12_0/bd1_xlconstant_12_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd1_xlconstant_12_0 || ORIG_REF_NAME==bd1_xlconstant_12_0} -quiet] -quiet

# IP: bd/bd1/ip/bd1_xlconstant_8_0/bd1_xlconstant_8_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd1_xlconstant_8_0 || ORIG_REF_NAME==bd1_xlconstant_8_0} -quiet] -quiet

# IP: bd/bd1/ip/bd1_SerializerAXI_0_0/bd1_SerializerAXI_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd1_SerializerAXI_0_0 || ORIG_REF_NAME==bd1_SerializerAXI_0_0} -quiet] -quiet

# IP: bd/bd1/ip/bd1_clk_wiz_0_0/bd1_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd1_clk_wiz_0_0 || ORIG_REF_NAME==bd1_clk_wiz_0_0} -quiet] -quiet

# IP: bd/bd1/ip/bd1_ila_0_0/bd1_ila_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd1_ila_0_0 || ORIG_REF_NAME==bd1_ila_0_0} -quiet] -quiet

# XDC: bd/bd1/bd1_ooc.xdc
